export const ADD_PRODUCTS="ADD_PRODUCTS";
export const ADD_CART_ITEMS="ADD_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const ADD_AMOUNT = 'ADD_AMOUNT';
export const DEDUCT_AMOUNT = 'DEDUCT_AMOUNT';